// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ressource_API.Common.Data;

#nullable disable

namespace Ressource_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203131426_RemovedPasswordSalt")]
    partial class RemovedPasswordSalt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("UserId", "EventId")
                        .HasName("event_member_pk");

                    b.HasIndex("EventId");

                    b.ToTable("event_member", (string)null);
                });

            modelBuilder.Entity("PollVote", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PollOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("poll_option_id");

                    b.HasKey("UserId", "PollOptionId")
                        .HasName("poll_vote_pk");

                    b.HasIndex("PollOptionId");

                    b.ToTable("poll_vote", (string)null);
                });

            modelBuilder.Entity("QuestionAnswer", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("QuizzQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("quizz_question_id");

                    b.HasKey("UserId", "QuizzQuestionId")
                        .HasName("question_answer_pk");

                    b.HasIndex("QuizzQuestionId");

                    b.ToTable("question_answer", (string)null);
                });

            modelBuilder.Entity("RessourceFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.HasKey("UserId", "RessourceId")
                        .HasName("ressource_favorite_pk");

                    b.HasIndex("RessourceId");

                    b.ToTable("ressource_favorite", (string)null);
                });

            modelBuilder.Entity("RessourceLike", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.HasKey("UserId", "RessourceId")
                        .HasName("ressource_like_pk");

                    b.HasIndex("RessourceId");

                    b.ToTable("ressource_like", (string)null);
                });

            modelBuilder.Entity("RessourceTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.HasKey("TagId", "RessourceId")
                        .HasName("ressource_tag_pk");

                    b.HasIndex("RessourceId");

                    b.ToTable("ressource_tag", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Addresses.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("addresses_pk");

                    b.HasIndex("CityId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Articles.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.HasKey("Id")
                        .HasName("articles_pk");

                    b.HasIndex("RessourceId");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.BackofficeLogLevels.Models.BackofficeLogLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("backoffice_log_levels_pk");

                    b.ToTable("backoffice_log_levels", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.BackofficeLogs.Models.BackofficeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BackofficeLogLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("backoffice_log_level_id");

                    b.Property<Guid>("BackofficeOperationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("backoffice_operation_type_id");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("LogContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("log_content");

                    b.HasKey("Id")
                        .HasName("backoffice_logs_pk");

                    b.HasIndex("BackofficeLogLevelId");

                    b.HasIndex("BackofficeOperationTypeId");

                    b.ToTable("backoffice_logs", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.BackofficeOperationTypes.Models.BackofficeOperationType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("backoffice_operation_types_pk");

                    b.ToTable("backoffice_operation_types", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Cities.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("department_code");

                    b.Property<float>("GpsLat")
                        .HasColumnType("real")
                        .HasColumnName("gps_lat");

                    b.Property<float>("GpsLng")
                        .HasColumnType("real")
                        .HasColumnName("gps_lng");

                    b.Property<string>("InseeCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("insee_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("cities_pk");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Comments.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("comments_pk");

                    b.HasIndex("CommentId");

                    b.HasIndex("RessourceId");

                    b.HasIndex("UserId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Departments.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("region_code");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("departments_pk");

                    b.HasIndex(new[] { "Code" }, "code_idx");

                    b.HasIndex(new[] { "RegionCode" }, "region_code_idx");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.EmailLogs.Models.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("operation_type");

                    b.Property<string>("ReceiverEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiver_email");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_email");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.HasKey("Id")
                        .HasName("email_logs_pk");

                    b.ToTable("email_logs", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Events.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start");

                    b.Property<string>("EventLink")
                        .HasColumnType("text")
                        .HasColumnName("event_link");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_virtual");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.HasKey("Id")
                        .HasName("events_pk");

                    b.HasIndex("RessourceId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.FriendsRequests.Models.FriendsRequest", b =>
                {
                    b.Property<Guid>("UserSenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_sender_id");

                    b.Property<Guid>("UserReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_receiver_id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("request_status");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("UserSenderId", "UserReceiverId")
                        .HasName("friends_requests_pk");

                    b.HasIndex("UserReceiverId");

                    b.ToTable("friends_requests", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Logins.Models.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("logins_pk");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Email" }, "email_idx");

                    b.ToTable("logins", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Notifications.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<bool>("MarkedAsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("marked_as_read");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pk");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.PasswordHistories.Models.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("PasswordInfosId")
                        .HasColumnType("uuid")
                        .HasColumnName("password_infos_id");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("passwords_history_pk");

                    b.HasIndex("PasswordInfosId");

                    b.ToTable("passwords_history", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.PasswordInfos.Models.PasswordInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<DateTime?>("ResetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_date");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("passwords_infos_pk");

                    b.HasIndex("UserId");

                    b.ToTable("passwords_infos", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.PollOptions.Models.PollOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("option");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid")
                        .HasColumnName("poll_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("polls_options_pk");

                    b.HasIndex("PollId");

                    b.ToTable("polls_options", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Polls.Models.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<long>("VoteCount")
                        .HasColumnType("bigint")
                        .HasColumnName("vote_count");

                    b.HasKey("Id")
                        .HasName("polls_pk");

                    b.HasIndex("RessourceId");

                    b.ToTable("polls", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.ProfilePictures.Models.ProfilePicture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("profiles_pictures_pk");

                    b.HasIndex("UserId");

                    b.ToTable("profiles_pictures", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.QuizzQuestions.Models.QuizzQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("PossibleAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("possible_answers");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("question");

                    b.Property<Guid>("QuizzId")
                        .HasColumnType("uuid")
                        .HasColumnName("quizz_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("quizzes_questions_pk");

                    b.HasIndex("QuizzId");

                    b.ToTable("quizzes_questions", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Quizzes.Models.Quizz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ParticipationCount")
                        .HasColumnType("bigint")
                        .HasColumnName("participation_count");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.HasKey("Id")
                        .HasName("quizzes_pk");

                    b.HasIndex("RessourceId");

                    b.ToTable("quizzes", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.RefreshTokens.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pk");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "token_hash_IDX");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Regions.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("regions_pk");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.ReportTypes.Models.ReportType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("reports_types_pk");

                    b.ToTable("reports_types", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Reports.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<bool>("IsCheckedByModerator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_checked_by_moderator");

                    b.Property<Guid>("ReportTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_type_id");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("reports_pk");

                    b.HasIndex("ReportTypeId");

                    b.HasIndex("RessourceId");

                    b.HasIndex("UserId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceConfidentialityTypes.Models.RessourceConfidentialityType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("ressources_confidentiality_types_pk");

                    b.ToTable("ressources_confidentiality_types", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceMedias.Models.RessourceMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("ressources_medias_pk");

                    b.HasIndex("RessourceId");

                    b.ToTable("ressources_medias", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceProgressions.Models.RessourceProgression", b =>
                {
                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsAside")
                        .HasColumnType("boolean")
                        .HasColumnName("is_aside");

                    b.Property<bool>("IsExploited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exploited");

                    b.HasKey("RessourceId", "UserId")
                        .HasName("ressource_progression_pk");

                    b.HasIndex("UserId");

                    b.ToTable("ressource_progression", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceStatuses.Models.RessourceStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("ressources_status_pk");

                    b.ToTable("ressources_status", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceTypes.Models.RessourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("ressource_types_pk");

                    b.ToTable("ressource_types", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Ressources.Models.Ressource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("RessourceConfidentialityTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_confidentiality_type_id");

                    b.Property<Guid>("RessourceStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_status_id");

                    b.Property<Guid>("RessourceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_type_id");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("ressources_pk");

                    b.HasIndex("RessourceConfidentialityTypeId");

                    b.HasIndex("RessourceStatusId");

                    b.HasIndex("RessourceTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ressources", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.SessionMessages.Models.SessionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("sessions_messages_pk");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("sessions_messages", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Sessions.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<string>("IdWs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_ws");

                    b.Property<Guid>("RessourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ressource_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("sessions_pk");

                    b.HasIndex("RessourceId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Tags.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("tags_pk");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.UserRoles.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("RoleLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_label");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("users_roles_pk");

                    b.ToTable("users_roles", (string)null);
                });

            modelBuilder.Entity("Ressource_API.Features.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivationCode")
                        .HasColumnType("uuid")
                        .HasColumnName("activation_code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_time");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_role_id");

                    b.HasKey("Id")
                        .HasName("users_pk");

                    b.HasIndex("UserRoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EventMember", b =>
                {
                    b.HasOne("Ressource_API.Features.Events.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("event_member_event_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("event_member_user_id_fk");
                });

            modelBuilder.Entity("PollVote", b =>
                {
                    b.HasOne("Ressource_API.Features.PollOptions.Models.PollOption", null)
                        .WithMany()
                        .HasForeignKey("PollOptionId")
                        .IsRequired()
                        .HasConstraintName("poll_vote_poll_option_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("poll_vote_user_id_fk");
                });

            modelBuilder.Entity("QuestionAnswer", b =>
                {
                    b.HasOne("Ressource_API.Features.QuizzQuestions.Models.QuizzQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuizzQuestionId")
                        .IsRequired()
                        .HasConstraintName("question_answer_quizz_question_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("question_answer_user_id_fk");
                });

            modelBuilder.Entity("RessourceFavorite", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", null)
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("ressource_favorite_ressource_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("ressource_favorite_user_id_fk");
                });

            modelBuilder.Entity("RessourceLike", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", null)
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("ressource_like_ressource_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("ressource_like_user_id_fk");
                });

            modelBuilder.Entity("RessourceTag", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", null)
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("ressource_tag_ressource_id_fk");

                    b.HasOne("Ressource_API.Features.Tags.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("ressource_tag_tag_id_fk");
                });

            modelBuilder.Entity("Ressource_API.Features.Addresses.Models.Address", b =>
                {
                    b.HasOne("Ressource_API.Features.Cities.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("addresses_city_id_fk");

                    b.HasOne("Ressource_API.Features.Departments.Models.Department", "Department")
                        .WithMany("Addresses")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("addresses_department_id_fk");

                    b.HasOne("Ressource_API.Features.Regions.Models.Region", "Region")
                        .WithMany("Addresses")
                        .HasForeignKey("RegionId")
                        .IsRequired()
                        .HasConstraintName("addresses_region_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("addresses_user_id_fk");

                    b.Navigation("City");

                    b.Navigation("Department");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.Articles.Models.Article", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", "Ressource")
                        .WithMany("Articles")
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("articles_ressource_id_fk");

                    b.Navigation("Ressource");
                });

            modelBuilder.Entity("Ressource_API.Features.BackofficeLogs.Models.BackofficeLog", b =>
                {
                    b.HasOne("Ressource_API.Features.BackofficeLogLevels.Models.BackofficeLogLevel", "BackofficeLogLevel")
                        .WithMany("BackofficeLogs")
                        .HasForeignKey("BackofficeLogLevelId")
                        .IsRequired()
                        .HasConstraintName("backoffice_logs_backoffice_log_level_id_fk");

                    b.HasOne("Ressource_API.Features.BackofficeOperationTypes.Models.BackofficeOperationType", "BackofficeOperationType")
                        .WithMany("BackofficeLogs")
                        .HasForeignKey("BackofficeOperationTypeId")
                        .IsRequired()
                        .HasConstraintName("backoffice_logs_backoffice_operation_type_id_fk");

                    b.Navigation("BackofficeLogLevel");

                    b.Navigation("BackofficeOperationType");
                });

            modelBuilder.Entity("Ressource_API.Features.Comments.Models.Comment", b =>
                {
                    b.HasOne("Ressource_API.Features.Comments.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("comments_comment_id_fk");

                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", "Ressource")
                        .WithMany("Comments")
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("comments_ressource_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("comments_user_id_fk");

                    b.Navigation("ParentComment");

                    b.Navigation("Ressource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.Events.Models.Event", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", "Ressource")
                        .WithMany("Events")
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("events_ressource_id_fk");

                    b.Navigation("Ressource");
                });

            modelBuilder.Entity("Ressource_API.Features.FriendsRequests.Models.FriendsRequest", b =>
                {
                    b.HasOne("Ressource_API.Features.Users.Models.User", "UserReceiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("UserReceiverId")
                        .IsRequired()
                        .HasConstraintName("friends_requests_user_receiver_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", "UserSender")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("UserSenderId")
                        .IsRequired()
                        .HasConstraintName("friends_requests_user_sender_id_fk");

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("Ressource_API.Features.Logins.Models.Login", b =>
                {
                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("logins_user_id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.Notifications.Models.Notification", b =>
                {
                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("notifications_user_id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.PasswordHistories.Models.PasswordHistory", b =>
                {
                    b.HasOne("Ressource_API.Features.PasswordInfos.Models.PasswordInfo", "PasswordInfos")
                        .WithMany("PasswordsHistories")
                        .HasForeignKey("PasswordInfosId")
                        .IsRequired()
                        .HasConstraintName("passwords_history_password_infos_id_fk");

                    b.Navigation("PasswordInfos");
                });

            modelBuilder.Entity("Ressource_API.Features.PasswordInfos.Models.PasswordInfo", b =>
                {
                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("PasswordsInfos")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("passwords_infos_user_id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.PollOptions.Models.PollOption", b =>
                {
                    b.HasOne("Ressource_API.Features.Polls.Models.Poll", "Poll")
                        .WithMany("PollsOptions")
                        .HasForeignKey("PollId")
                        .IsRequired()
                        .HasConstraintName("polls_options_poll_id_fk");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Ressource_API.Features.Polls.Models.Poll", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", "Ressource")
                        .WithMany("Polls")
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("polls_ressource_id_fk");

                    b.Navigation("Ressource");
                });

            modelBuilder.Entity("Ressource_API.Features.ProfilePictures.Models.ProfilePicture", b =>
                {
                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("ProfilesPictures")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("profiles_pictures_user_id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.QuizzQuestions.Models.QuizzQuestion", b =>
                {
                    b.HasOne("Ressource_API.Features.Quizzes.Models.Quizz", "Quizz")
                        .WithMany("QuizzesQuestions")
                        .HasForeignKey("QuizzId")
                        .IsRequired()
                        .HasConstraintName("quizzes_questions_quizz_id_fk");

                    b.Navigation("Quizz");
                });

            modelBuilder.Entity("Ressource_API.Features.Quizzes.Models.Quizz", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", "Ressource")
                        .WithMany("Quizzes")
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("quizzes_ressource_id_fk");

                    b.Navigation("Ressource");
                });

            modelBuilder.Entity("Ressource_API.Features.RefreshTokens.Models.RefreshToken", b =>
                {
                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.Reports.Models.Report", b =>
                {
                    b.HasOne("Ressource_API.Features.ReportTypes.Models.ReportType", "ReportType")
                        .WithMany("Reports")
                        .HasForeignKey("ReportTypeId")
                        .IsRequired()
                        .HasConstraintName("reports_report_type_id_fk");

                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", "Ressource")
                        .WithMany("Reports")
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("reports_ressource_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("reports_user_id_fk");

                    b.Navigation("ReportType");

                    b.Navigation("Ressource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceMedias.Models.RessourceMedia", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", "Ressource")
                        .WithMany("RessourcesMedia")
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("ressources_medias_ressource_id_fk");

                    b.Navigation("Ressource");
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceProgressions.Models.RessourceProgression", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", "Ressource")
                        .WithMany("RessourceProgressions")
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("ressource_progression_ressource_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("RessourceProgressions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("ressource_progression_user_id_fk");

                    b.Navigation("Ressource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.Ressources.Models.Ressource", b =>
                {
                    b.HasOne("Ressource_API.Features.RessourceConfidentialityTypes.Models.RessourceConfidentialityType", "RessourceConfidentialityType")
                        .WithMany("Ressources")
                        .HasForeignKey("RessourceConfidentialityTypeId")
                        .IsRequired()
                        .HasConstraintName("ressources_ressource_confidentiality_type_id_fk");

                    b.HasOne("Ressource_API.Features.RessourceStatuses.Models.RessourceStatus", "RessourceStatus")
                        .WithMany("Ressources")
                        .HasForeignKey("RessourceStatusId")
                        .IsRequired()
                        .HasConstraintName("ressources_ressource_status_id_fk");

                    b.HasOne("Ressource_API.Features.RessourceTypes.Models.RessourceType", "RessourceType")
                        .WithMany("Ressources")
                        .HasForeignKey("RessourceTypeId")
                        .IsRequired()
                        .HasConstraintName("ressources_ressource_type_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("AuthoredRessources")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("ressources_user_id_fk");

                    b.Navigation("RessourceConfidentialityType");

                    b.Navigation("RessourceStatus");

                    b.Navigation("RessourceType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.SessionMessages.Models.SessionMessage", b =>
                {
                    b.HasOne("Ressource_API.Features.Sessions.Models.Session", "Session")
                        .WithMany("SessionsMessages")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("sessions_messages_session_id_fk");

                    b.HasOne("Ressource_API.Features.Users.Models.User", "User")
                        .WithMany("SessionsMessages")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("sessions_messages_user_id_fk");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ressource_API.Features.Sessions.Models.Session", b =>
                {
                    b.HasOne("Ressource_API.Features.Ressources.Models.Ressource", "Ressource")
                        .WithMany("Sessions")
                        .HasForeignKey("RessourceId")
                        .IsRequired()
                        .HasConstraintName("sessions_ressource_id_fk");

                    b.Navigation("Ressource");
                });

            modelBuilder.Entity("Ressource_API.Features.Users.Models.User", b =>
                {
                    b.HasOne("Ressource_API.Features.UserRoles.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .IsRequired()
                        .HasConstraintName("users_user_role_id_fk");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Ressource_API.Features.BackofficeLogLevels.Models.BackofficeLogLevel", b =>
                {
                    b.Navigation("BackofficeLogs");
                });

            modelBuilder.Entity("Ressource_API.Features.BackofficeOperationTypes.Models.BackofficeOperationType", b =>
                {
                    b.Navigation("BackofficeLogs");
                });

            modelBuilder.Entity("Ressource_API.Features.Cities.Models.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Ressource_API.Features.Comments.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Ressource_API.Features.Departments.Models.Department", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Ressource_API.Features.PasswordInfos.Models.PasswordInfo", b =>
                {
                    b.Navigation("PasswordsHistories");
                });

            modelBuilder.Entity("Ressource_API.Features.Polls.Models.Poll", b =>
                {
                    b.Navigation("PollsOptions");
                });

            modelBuilder.Entity("Ressource_API.Features.Quizzes.Models.Quizz", b =>
                {
                    b.Navigation("QuizzesQuestions");
                });

            modelBuilder.Entity("Ressource_API.Features.Regions.Models.Region", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Ressource_API.Features.ReportTypes.Models.ReportType", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceConfidentialityTypes.Models.RessourceConfidentialityType", b =>
                {
                    b.Navigation("Ressources");
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceStatuses.Models.RessourceStatus", b =>
                {
                    b.Navigation("Ressources");
                });

            modelBuilder.Entity("Ressource_API.Features.RessourceTypes.Models.RessourceType", b =>
                {
                    b.Navigation("Ressources");
                });

            modelBuilder.Entity("Ressource_API.Features.Ressources.Models.Ressource", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("Events");

                    b.Navigation("Polls");

                    b.Navigation("Quizzes");

                    b.Navigation("Reports");

                    b.Navigation("RessourceProgressions");

                    b.Navigation("RessourcesMedia");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Ressource_API.Features.Sessions.Models.Session", b =>
                {
                    b.Navigation("SessionsMessages");
                });

            modelBuilder.Entity("Ressource_API.Features.UserRoles.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Ressource_API.Features.Users.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AuthoredRessources");

                    b.Navigation("Comments");

                    b.Navigation("Logins");

                    b.Navigation("Notifications");

                    b.Navigation("PasswordsInfos");

                    b.Navigation("ProfilesPictures");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reports");

                    b.Navigation("RessourceProgressions");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("SessionsMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
